FROM python:3.11-slim

WORKDIR /app


COPY run.py .
COPY requirements.txt .

RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

EXPOSE 5001

CMD ["python", "run.py"]
